### ISSUE TITLE
Admin panel: 404 on clicking on "admins" tab

### ISSUE THREAD

**Issue by brunobuddy** [mnfst/llm-gateway#110]
- Add manifest with the `npx add-manifest` script
- In your admin panel, click on "admins" tab on the sidebar
- The page goes 404

**Comment by brunobuddy** [comment]
It seems that the issue only occurs on the first connection. Related: the email of the connected user on the bottom left does not appear too.

**Comment by SebConejo** [comment]
@brunobuddy To me, it works well. May I close this issue ?

**Comment by brunobuddy** [comment]
@SebConejo yes it has already been fixed
