### ISSUE TITLE
Can't use sdk in astro react island

### ISSUE THREAD

**Issue by caeg0n** [mnfst/llm-gateway#119]
chrome console print when import Manifest from '@mnfst/sdk' in react island:
Error hydrating /src/components/react/oficios/OfficialDocuments.jsx SyntaxError: SyntaxError: The requested module '/node_modules/url/url.js?v=8a8d258f' does not provide an export named 'default'

**Comment by SebConejo** [comment]
Hi @caeg0n. Thanks for your feedback. Indeed, we haven't tested it with Astro. We'll take a closer look soon. We're in the process of gathering all the feedback from developers to understand what matters most. So we're interested in this information. We'll also do our best to open up the project to contributions. This could speed up the resolution of this kind of bug.

**Comment by brunobuddy** [comment]
Thank you @caeg0n, it seems that it is because the SDK is in commonjs and not in ESM. We will do the update soon.

**Comment by brunobuddy** [comment]
Hello @caeg0n the last version of the JS SDK is compatible with Astro !

I also created a quick start guide: https://manifest.build/docs/astro
