### ISSUE TITLE
style: Update the look and feel of the `responses` title on the API docs to make it easier to read

### ISSUE THREAD

**Issue by SebConejo** [mnfst/llm-gateway#133]
The structure of the API documentation is difficult to follow.

When testing an endpoint, the API documentation first displays the test response, followed by a list of possible responses. Both sections have titles, but these titles are not very prominent. They are written in small text with minimal whitespace above them, making them hard to notice. The separation between these two sections could be improved.

****
**My suggestions:**
- [ ] Increase the white space above the title. 
- [ ] If it's not enough visible, try to use a different color, or add a separator line, or even try adding emojis.

**Remarks**
- It looks unnecessary to increase the font size as the parent title is small too. 

![Capture d’écran 2024-08-30 à 10 45 51](https://github.com/user-attachments/assets/b29f0654-0bbb-4c7b-90db-e58b45274674)

![Capture d’écran 2024-09-23 à 14 34 59](https://github.com/user-attachments/assets/4604ec07-7cea-47aa-913e-12af23640762)

**Comment by LoayTarek5** [comment]
@SebConejo Hi SebConejo I am happy to contribute to this issue and solve it, could i

**Comment by SebConejo** [comment]
Hi @LoayTarek5. I assigned you to the issue 👍

**Comment by LoayTarek5** [comment]
@SebConejo should I solve it and merge at beginning Hacktoberfest or is it ok to pull/merge now

**Comment by SebConejo** [comment]
@LoayTarek5 If the work is ready and doesn't need to be tied to Hacktoberfest, you can do it now. We will review it this week. If your goal is to "earn points" during Hacktoberfest, you have to wait for October 1st before making a PR.

**Comment by LoayTarek5** [comment]
@SebConejo Oh, I am sorry. By mistake I removed myself, could you assign it to me again. Anyway, I will work on this issue now.

**Comment by LoayTarek5** [comment]
@SebConejo Sorry, I couldn't find the file I need to edit to fix the style. Can you please tell me which file to edit?

**Comment by SebConejo** [comment]
> @SebConejo Sorry, I couldn't find the file I need to edit to fix the style. Can you please tell me which file to edit?

@LoayTarek5 The file is this one: [packages\core\manifest\src\main.ts](https://github.com/mnfst/manifest/blob/master/packages/core/manifest/src/main.ts)

We use swaggerUI for now. The css is writtten directly in this typescript file.

**Comment by LoayTarek5** [comment]
![image](https://github.com/user-attachments/assets/41f18b9e-7282-455a-b107-3f0d2a9e3b3a)

![image](https://github.com/user-attachments/assets/87e59940-3f8d-426a-b8da-4ca69bf39d77)
@SebConejo Is it good?

**Comment by SebConejo** [comment]
@LoayTarek5 Thank you for your proposal. Here are my comments:

- Could you use this blue instead: #2430F0 ? Or this one if you think it's easier to read: #1eb1e8. Those blues are in the toolkit.
- The change should only be made to h4. Not on response headers, response bodies. You see what I mean?
![370774766-41f18b9e-7282-455a-b107-3f0d2a9e3b3a](https://github.com/user-attachments/assets/883315cb-57cd-4efd-b2fb-9e4fe9167a6c)

**Comment by LoayTarek5** [comment]
@SebConejo ok i will use #1eb1e8 i think it is better
Is this how it should look?
![image](https://github.com/user-attachments/assets/b81745aa-3459-429a-a8c9-30dfedfb9245)

or you want only edit on this :
![image](https://github.com/user-attachments/assets/afc6caca-12b2-4d25-af43-ab7a69573070)
