### ISSUE TITLE
Update Twitter Logo to New "X" Branding

### ISSUE THREAD

**Issue by Piyush-Goenka** [mnfst/llm-gateway#187]
# Issue: Update Twitter Logo to New "X" Logo

## Description
While scrolling down the page, the Twitter logo displayed is still the older version. We need to update it to the new logo, which is now referred to as "X".

## Steps to Reproduce
1. Navigate to the https://manifest.build
2. Scroll down the page.
3. Observe the Twitter logo.

## Expected Behavior
The page should display the new "X" logo instead of the older Twitter logo.

## Current Behavior
The old Twitter logo is still visible when scrolling down.

## Screenshot
<img width="257" alt="Screenshot 2024-09-28 at 12 56 52 AM" src="https://github.com/user-attachments/assets/59a19101-2732-4a30-8cdd-e412783708b8">

## Suggested Solution
Replace the existing Twitter logo with the new "X" logo in the relevant files.

Thank you!

**Comment by Piyush-Goenka** [comment]
@SebConejo I would like to work on this issue.

**Comment by brunobuddy** [comment]
@Piyush-Goenka go ahead, the concerned repo is https://github.com/mnfst/website

You can follow the same [contributing rules](https://github.com/mnfst/manifest/blob/master/CONTRIBUTING.md) as in this repo !

**Comment by nitesh2920** [comment]
If this issue is still open, can I work on it?  @brunobuddy @SebConejo

**Comment by Piyush-Goenka** [comment]
@brunobuddy 
I am unable to solve this issue please assign this issue to someone else .

**Comment by nitesh2920** [comment]
@brunobuddy assign me.

**Comment by SebConejo** [comment]
@nitesh2920 we use lineicon. This font doesn't contain the x icon for now. Maybe we could just use an svg icon to display this one instead of calling another whole font-icon.

**Comment by nitesh2920** [comment]
@SebConejo yeah I just wanted to ask that question.

**Comment by nitesh2920** [comment]
@SebConejo I have one question I have to raise a PR in https://github.com/mnfst/website this repo instead of this as it is for backend only.

**Comment by brunobuddy** [comment]
@nitesh2920 yes the repo is https://github.com/mnfst/website

**Comment by nitesh2920** [comment]
@brunobuddy so I have to first create  a issue there then raise a PR for that issue.

**Comment by nitesh2920** [comment]
@brunobuddy @SebConejo raised the PR please check https://github.com/mnfst/website/pull/29#issue-2576495831

**Comment by brunobuddy** [comment]
Hello @nitesh2920 sorry this is not applicable anymore as we are not displaying personal accounts on the [website](https://manifest.build)
