### ISSUE TITLE
File uploads: Uploaded files with spaces in the filename are not URL-encoded, making them inaccessible for download

### ISSUE THREAD

**Issue by SebConejo** [mnfst/llm-gateway#191]
When I upload a file with spaces in its name, the spaces are not URL-encoded. This causes issues when trying to download the file later, as URLs cannot handle spaces directly. For example, a file named "test 02" should have its spaces encoded as %20, but it currently isn't, making the file inaccessible for download.

1. Here we can note the file we pushed contains white spaces.
<img width="491" alt="Capture d’écran 2024-10-01 à 23 34 54" src="https://github.com/user-attachments/assets/31a03f10-7bc9-4c49-840c-53ec24f3c147">

2. The response we see when trying to download this file
`
{
  "message": "Cannot GET /storage/cats/certificate/Oct2024/1s8ug193nm1qyb7v3-Tool%20",
  "error": "Not Found",
  "statusCode": 404
}
`

**Comment by brunobuddy** [comment]
@SebConejo correct we need to slugify the name before storing it
