### ISSUE TITLE
Pre-fill credentials on admin panel onboarding

### ISSUE THREAD

**Issue by brunobuddy** [mnfst/llm-gateway#193]
It is hard to find the credentials in the page.

We could create an env variable (in .env) that tells the client that it has to suggest the default admin user in the login page fields

It is true on stackblitz demo but also on local install

![image](https://github.com/user-attachments/assets/8a8b34c3-6961-4705-aa7e-fe78be076325)

**Comment by SebConejo** [comment]
@brunobuddy What about those who will create other accounts? Will they be prefilled with the admin credentials? It seems strange to me.

**Comment by brunobuddy** [comment]
@SebConejo the seeder always create an `admin@manifest.build` user so every DB seeded in local/stackblitz/contribution will include the `admin@manifest.build` admin
