### ISSUE TITLE
Add Link to Contributing Guidelines in README

### ISSUE THREAD

**Issue by HalfToothed** [mnfst/llm-gateway#210]
**Describe the bug**
The README is missing a welcoming message for contributors. Adding a message that encourages contributions and links to the contributing guidelines will make it easier for new contributors to engage and quickly find the relevant information.

**To Reproduce**
1. Open the repository.
2. Navigate to the README file.
3. Look for a section mentioning how to contribute or a link to the contributing guidelines.

**Expected behavior**
The README should contain a line like:

    We welcome contributions! Please see our Contributing Guidelines for more information.

This will encourage participation and make it easier to locate the contributing guidelines.

**Screenshots**
N/A

**Code snippets**
Not applicable for this issue.

**Additional context**
Adding this line will improve the onboarding experience for contributors and ensure they can easily find the contributing guidelines.

**Comment by brunobuddy** [comment]
Good idea @HalfToothed, do you want to do the PR ?

**Comment by HalfToothed** [comment]
@brunobuddy  yes sure, please assign it to me
