### ISSUE TITLE
Doc: Enums, a coma is missing 

### ISSUE THREAD

**Issue by SebConejo** [mnfst/llm-gateway#97]
After 'Pending', a coma should be written.

![Capture d’écran 2023-12-01 à 19 04 13](https://github.com/casejs/CASE/assets/11723962/cd646808-3c77-4c71-b088-d43cab571ffe)

**Comment by Tjs002** [comment]
Hi @SebConejo can I work on this?

**Comment by SebConejo** [comment]
@Tjs002 of course 👍

**Comment by Tjs002** [comment]
After 'WorkInProgress' a coma should also be written, right?

**Comment by Tjs002** [comment]
I have opened a PR you can check it @SebConejo.
